# general
gpu_id: 0
use_gpu: True  # MPS works with PyTorch 2.4+
seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: False
save_dataset: False
save_dataloaders: False

# training settings
epochs: 200
train_batch_size: 256
learner: adam
learning_rate: 0.001
neg_sampling: ~
eval_step: 1
stopping_step: 20
clip_grad_norm: ~
weight_decay: 0.0

# evaluation settings
eval_args:
  split: {'RS': [0.8,0.1,0.1]}
  group_by: user
  order: TO
  mode: full
repeatable: True
metrics: ["Recall","MRR","NDCG","Hit","Precision"]
topk: [10]
valid_metric: MRR@10
valid_metric_bigger: True
eval_batch_size: 4096
loss_decimal_place: 4
metric_decimal_place: 4

# model - SASRec
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'CE'
label_smoothing: 0.1

# dataset
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
seq_len: ~
LABEL_FIELD: label
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id

load_col:
    inter: [user_id, item_id, timestamp]
unload_col: ~
unused_col: ~

# Filtering
rm_dup_inter: ~
val_interval: ~
filter_inter_by_user_or_item: True
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# Preprocessing
normalize_all: True
