# ml-1m NGCF config
gpu_id: 0
use_gpu: True
seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
save_dataloaders: False

# dataset
load_col:
    inter: [user_id, item_id]
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id

# Filtering
val_interval: ~
filter_inter_by_user_or_item: True
user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"

# Model - NGCF specific
embedding_size: 64
hidden_size_list: [64, 64, 64]
node_dropout: 0.0
message_dropout: 0.1
reg_weight: 1e-05

# training settings
epochs: 300
train_batch_size: 1024
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 20
clip_grad_norm: ~
weight_decay: 0.0

# BPR requires negative sampling
neg_sampling:
    uniform: 1

# evaluation settings
eval_args:
  split: {'RS': [0.8,0.1,0.1]}
  group_by: user
  order: RO
  mode: full

repeatable: True
metrics: ["Recall","NDCG","Hit"]
topk: [10, 20]
valid_metric: Recall@20
valid_metric_bigger: True
eval_batch_size: 4096

# wandb logging
use_wandb: True
wandb_project: 'recbole-ls'
